repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.16.3
    hooks:
      - id: cargo-deny
        args: ["--all-features", "check"]

  - repo: local
    hooks:
      - id: typos
        name: typos
        entry: typos
        language: system
        types: [text]
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo nextest
        entry: cargo nextest run --all-features --no-tests warn
        language: system
        types: [rust]
        pass_filenames: false
