[files]
extend-exclude = [
    "netw-ib-ox-ag-5.39.0/",
    "CHANGELOG.md",
    "target/",
]

[default.extend-words]
shw = "shw"
predictible = "predictible"
hashi = "hashi"
ringi = "ringi"
ipsi = "ipsi"
ethsi = "ethsi"
portsi = "portsi"
