[package]
name = "nz"
description = "Network toolbox CLI (netwox successor)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nz-net = { path = "../nz-net", features = ["system-inventory"] }
nz-arg = { path = "../nz-arg" }

[lints]
workspace = true
