//! 编译期工具登记表（由 specs 汇总生成逻辑维护；见 `registry/mod.rs`）。
//!
//! 请勿手改发布规则以外的元数据而不对照 `spec/netwox/`。

use super::{PublishKind, ToolEntry, ToolId};

/// 默认编入二进制的工具表（含 hidden；不含 deferred）。
pub static TOOL_ENTRIES: &[ToolEntry] = &[
    ToolEntry {
        id: ToolId(0),
        title: "Obtain information needed by netwag",
        suggested_name: "gui-info",
        publish: PublishKind::Hidden,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(1),
        title: "Display network configuration",
        suggested_name: "net-conf",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(2),
        title: "Display debugging information",
        suggested_name: "debug-info",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(3),
        title: "Display information about an IP address or a hostname",
        suggested_name: "host-info",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(4),
        title: "Display information about an Ethernet address",
        suggested_name: "eth-info",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(5),
        title: "Obtain Ethernet addresses of computers in an IP list",
        suggested_name: "arp-scan",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(6),
        title: "Display how to reach an IP address",
        suggested_name: "route-to",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(7),
        title: "Sniff",
        suggested_name: "sniff",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(8),
        title: "Sniff and display open ports",
        suggested_name: "sniff-ports",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(9),
        title: "Sniff and display Ethernet addresses",
        suggested_name: "sniff-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(10),
        title: "Sniff and display network statistics",
        suggested_name: "sniff-stats",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(11),
        title: "Sniff and verify checksums",
        suggested_name: "sniff-csum",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(12),
        title: "Display which values to use for netwox parameters",
        suggested_name: "param-values",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(13),
        title: "Obtain DLT type for sniff and spoof for each device",
        suggested_name: "dlt-info",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(14),
        title: "Spoof a record",
        suggested_name: "record-spoof",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(15),
        title: "Display content of a record",
        suggested_name: "record-show",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(16),
        title: "Convert a record",
        suggested_name: "record-convert",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(17),
        title: "Recompute checksums of packets in a record",
        suggested_name: "record-csum",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(18),
        title: "Reassemble IP packets of a record, and reorder TCP flow",
        suggested_name: "record-reasm",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(19),
        title: "Extract a range of packets from a record",
        suggested_name: "record-slice",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(20),
        title: "Search for strings in packets from a record",
        suggested_name: "record-grep",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(21),
        title: "Convert a number",
        suggested_name: "conv-num",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(22),
        title: "Convert a string",
        suggested_name: "conv-str",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(23),
        title: "Display ASCII table",
        suggested_name: "ascii-table",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(24),
        title: "Convert IP addresses ranges",
        suggested_name: "ip-calc",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(25),
        title: "Test if a directory is secure",
        suggested_name: "dir-secure",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(26),
        title: "Dump a file",
        suggested_name: "file-dump",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(27),
        title: "Compute MD5 of a file",
        suggested_name: "file-md5",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(28),
        title: "Convert a binary file to readable and editable file",
        suggested_name: "bin-to-mixed",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(29),
        title: "Convert a readable and editable file to a binary file",
        suggested_name: "mixed-to-bin",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(30),
        title: "Convert a file from unix to dos",
        suggested_name: "unix2dos",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(31),
        title: "Convert a file from dos to unix",
        suggested_name: "dos2unix",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(32),
        title: "Spoof Ethernet packet",
        suggested_name: "spoof-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(33),
        title: "Spoof EthernetArp packet",
        suggested_name: "spoof-eth-arp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(34),
        title: "Spoof EthernetIp4 packet",
        suggested_name: "spoof-eth-ip4",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(35),
        title: "Spoof EthernetIp4Udp packet",
        suggested_name: "spoof-eth-ip4-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(36),
        title: "Spoof EthernetIp4Tcp packet",
        suggested_name: "spoof-eth-ip4-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(37),
        title: "Spoof EthernetIp4Icmp4 packet",
        suggested_name: "spoof-eth-ip4-icmp4",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(38),
        title: "Spoof Ip4 packet",
        suggested_name: "spoof-ip4",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(39),
        title: "Spoof Ip4Udp packet",
        suggested_name: "spoof-ip4-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(40),
        title: "Spoof Ip4Tcp packet",
        suggested_name: "spoof-ip4-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(41),
        title: "Spoof Ip4Icmp4 packet",
        suggested_name: "spoof-ip4-icmp4",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(42),
        title: "Spoof of packet samples : fragment",
        suggested_name: "spoof-sample",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(43),
        title: "Spoof of packet samples : fragment, ip4opt:noop",
        suggested_name: "spoof-sample-noop",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(44),
        title: "Spoof of packet samples : fragment, ip4opt:rr",
        suggested_name: "spoof-sample-rr",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(45),
        title: "Spoof of packet samples : fragment, ip4opt:lsrr",
        suggested_name: "spoof-sample-lsrr",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(46),
        title: "Spoof of packet samples : fragment, ip4opt:ts",
        suggested_name: "spoof-sample-ts",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(47),
        title: "Spoof of packet samples : fragment, ip4opt:ipts",
        suggested_name: "spoof-sample-ipts",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(48),
        title: "Spoof of packet samples : fragment, ip4opt:ippts",
        suggested_name: "spoof-sample-ippts",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(49),
        title: "Ping ICMP",
        suggested_name: "ping-icmp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(50),
        title: "Ping ICMP (EthIP spoof)",
        suggested_name: "ping-icmp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(51),
        title: "Ping TCP",
        suggested_name: "ping-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(52),
        title: "Ping TCP (EthIp spoof)",
        suggested_name: "ping-tcp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(53),
        title: "Ping UDP",
        suggested_name: "ping-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(54),
        title: "Ping UDP (EthIp spoof)",
        suggested_name: "ping-udp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(55),
        title: "Ping ARP",
        suggested_name: "ping-arp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(56),
        title: "Ping ARP (EthIp spoof)",
        suggested_name: "ping-arp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(57),
        title: "Traceroute ICMP",
        suggested_name: "trace-icmp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(58),
        title: "Traceroute ICMP (EthIP spoof)",
        suggested_name: "trace-icmp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(59),
        title: "Traceroute TCP",
        suggested_name: "trace-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(60),
        title: "Traceroute TCP (EthIp spoof)",
        suggested_name: "trace-tcp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(61),
        title: "Traceroute UDP",
        suggested_name: "trace-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(62),
        title: "Traceroute UDP (EthIp spoof)",
        suggested_name: "trace-udp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(63),
        title: "Traceroute on a specified IP protocol",
        suggested_name: "trace-ipproto",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(64),
        title: "Traceroute on a specified IP protocol (EthIp spoof)",
        suggested_name: "trace-ipproto-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(65),
        title: "Scan ICMP",
        suggested_name: "scan-icmp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(66),
        title: "Scan ICMP (EthIP spoof)",
        suggested_name: "scan-icmp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(67),
        title: "Scan TCP",
        suggested_name: "scan-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(68),
        title: "Scan TCP (EthIp spoof)",
        suggested_name: "scan-tcp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(69),
        title: "Scan UDP",
        suggested_name: "scan-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(70),
        title: "Scan UDP (EthIp spoof)",
        suggested_name: "scan-udp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(71),
        title: "Scan ARP",
        suggested_name: "scan-arp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(72),
        title: "Scan ARP (EthIp spoof)",
        suggested_name: "scan-arp-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(87),
        title: "TCP client",
        suggested_name: "tcp-client",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(88),
        title: "UDP client",
        suggested_name: "udp-client",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(89),
        title: "TCP server",
        suggested_name: "tcp-server",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(90),
        title: "UDP server",
        suggested_name: "udp-server",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(91),
        title: "TCP server multiclients",
        suggested_name: "tcp-mulser",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(92),
        title: "UDP server multiclients",
        suggested_name: "udp-mulser",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(93),
        title: "TCP remote administration server",
        suggested_name: "remadm-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(94),
        title: "TCP remote administration client (exec)",
        suggested_name: "remadm-exec",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(95),
        title: "TCP remote administration client (get file)",
        suggested_name: "remadm-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(96),
        title: "TCP remote administration client (put file)",
        suggested_name: "remadm-put",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(97),
        title: "SYSLOG client",
        suggested_name: "syslog-client",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(99),
        title: "TELNET client",
        suggested_name: "telnet-client",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(100),
        title: "TELNET client executing one or several commands",
        suggested_name: "telnet-exec",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(102),
        title: "Query a DNS server",
        suggested_name: "dns-query",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(103),
        title: "Obtain version of a Bind DNS server",
        suggested_name: "dns-bind-version",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(104),
        title: "DNS server always answering same values",
        suggested_name: "dns-fixed",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(105),
        title: "Sniff and send DNS answers",
        suggested_name: "dns-answer",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(106),
        title: "Send an email",
        suggested_name: "smtp-send",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(107),
        title: "Post a newsgroup message",
        suggested_name: "nntp-post",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(108),
        title: "List newsgroups",
        suggested_name: "nntp-list",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(109),
        title: "Download messages",
        suggested_name: "nntp-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(110),
        title: "Ethernet bridge limiting flow",
        suggested_name: "eth-bridge",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(111),
        title: "FTP listing a directory",
        suggested_name: "ftp-ls",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(112),
        title: "FTP client : get a file",
        suggested_name: "ftp-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(113),
        title: "FTP client : put a file",
        suggested_name: "ftp-put",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(114),
        title: "FTP client : del a file",
        suggested_name: "ftp-rm",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(115),
        title: "FTP client : get a directory recursively",
        suggested_name: "ftp-get-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(116),
        title: "FTP client : put a directory recursively",
        suggested_name: "ftp-put-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(117),
        title: "FTP client : del a directory recursively",
        suggested_name: "ftp-rm-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(118),
        title: "HTTP GET",
        suggested_name: "http-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(119),
        title: "HTTP HEAD",
        suggested_name: "http-head",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(120),
        title: "HTTP POST",
        suggested_name: "http-post",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(121),
        title: "HTTP PUT",
        suggested_name: "http-put",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(122),
        title: "HTTP DELETE",
        suggested_name: "http-delete",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(123),
        title: "HTTP TRACE",
        suggested_name: "http-trace",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(124),
        title: "HTTP OPTIONS",
        suggested_name: "http-options",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(125),
        title: "HTTP server",
        suggested_name: "http-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(126),
        title: "HTTP remote administration server",
        suggested_name: "remadm-http",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(127),
        title: "Cypher/decypher a file using a xor",
        suggested_name: "file-xor",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(128),
        title: "Split a file in smaller chunks",
        suggested_name: "file-split",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(129),
        title: "Reassemble chunks of a file",
        suggested_name: "file-join",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(133),
        title: "Convert an url/uri",
        suggested_name: "url-convert",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(134),
        title: "Obtain urls/uris in a HTML file",
        suggested_name: "html-urls",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(135),
        title: "Convert urls/uris in a HTML file to absolute urls",
        suggested_name: "html-abs",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(136),
        title: "Web download (http://... or ftp://...)",
        suggested_name: "web-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(137),
        title: "Create a sample configuration file for tool 138",
        suggested_name: "spider-conf-sample",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(138),
        title: "Web spider (use configuration file created by tool 137)",
        suggested_name: "spider-conf",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: true,
    },
    ToolEntry {
        id: ToolId(139),
        title: "Web spider on command line (fully recursive)",
        suggested_name: "spider-full",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: true,
    },
    ToolEntry {
        id: ToolId(140),
        title: "Spoof EthernetIp6 packet",
        suggested_name: "spoof-eth-ip6",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(141),
        title: "Spoof EthernetIp6Udp packet",
        suggested_name: "spoof-eth-ip6-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(142),
        title: "Spoof EthernetIp6Tcp packet",
        suggested_name: "spoof-eth-ip6-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(143),
        title: "Spoof EthernetIp6Icmp6 packet",
        suggested_name: "spoof-eth-ip6-icmp6",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(144),
        title: "Spoof Ip6 packet",
        suggested_name: "spoof-ip6",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(145),
        title: "Spoof Ip6Udp packet",
        suggested_name: "spoof-ip6-udp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(146),
        title: "Spoof Ip6Tcp packet",
        suggested_name: "spoof-ip6-tcp",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(147),
        title: "Spoof Ip6Icmp6 packet",
        suggested_name: "spoof-ip6-icmp6",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(148),
        title: "Ping ICMP6 Neighbor Discovery",
        suggested_name: "ping-nsolic",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(149),
        title: "Ping ICMP6 Neighbor Discovery (EthIp spoof)",
        suggested_name: "ping-nsolic-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(150),
        title: "Scan ICMP6 Neighbor Discovery",
        suggested_name: "scan-nsolic",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(151),
        title: "Scan ICMP6 Neighbor Discovery (EthIp spoof)",
        suggested_name: "scan-nsolic-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(152),
        title: "Interactive IRC client",
        suggested_name: "irc-client",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(153),
        title: "IRC client listing channels",
        suggested_name: "irc-list",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(154),
        title: "IRC client listening on a channel",
        suggested_name: "irc-listen",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(155),
        title: "Network performance measurement : TCP server",
        suggested_name: "perf-tcp-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(156),
        title: "Network performance measurement : TCP client",
        suggested_name: "perf-tcp-client",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(157),
        title: "Network performance measurement : UDP server",
        suggested_name: "perf-udp-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(158),
        title: "Network performance measurement : UDP client",
        suggested_name: "perf-udp-client",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(159),
        title: "SNMP Get",
        suggested_name: "snmp-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(160),
        title: "SNMP Walk",
        suggested_name: "snmp-walk",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(161),
        title: "SNMP Trap",
        suggested_name: "snmp-trap",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(162),
        title: "SNMP Trap2",
        suggested_name: "snmp-trap2",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(163),
        title: "SNMP Inform",
        suggested_name: "snmp-inform",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(164),
        title: "SNMP Set",
        suggested_name: "snmp-set",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(165),
        title: "TFTP client : get a file",
        suggested_name: "tftp-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(166),
        title: "TFTP client : put a file",
        suggested_name: "tftp-put",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(167),
        title: "TFTP server",
        suggested_name: "tftp-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(168),
        title: "FTP server",
        suggested_name: "ftp-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(169),
        title: "Display simple network configuration easy to parse",
        suggested_name: "net-conf-simple",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(170),
        title: "TELNET server",
        suggested_name: "telnet-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(171),
        title: "DHCP client",
        suggested_name: "dhcp-client",
        publish: PublishKind::Release,
        needs_stdin: true,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(172),
        title: "List articles range",
        suggested_name: "nntp-range",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(173),
        title: "Download overview",
        suggested_name: "nntp-over",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(174),
        title: "FTP client : get a file and check its MD5",
        suggested_name: "ftp-get-md5",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(175),
        title: "Web download (http://... or ftp://...) and check its MD5",
        suggested_name: "web-get-md5",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(176),
        title: "TFTP client : get a file and check its MD5",
        suggested_name: "tftp-get-md5",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(177),
        title: "Check if a SMTP server is up",
        suggested_name: "smtp-probe",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(178),
        title: "Check if an IRC server is up",
        suggested_name: "irc-probe",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(179),
        title: "DHCP client requesting an INFORM",
        suggested_name: "dhcp-inform",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(180),
        title: "SNTP client obtaining time",
        suggested_name: "sntp-client",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(181),
        title: "SNTP server",
        suggested_name: "sntp-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(182),
        title: "Obtain size of a web file (http://... or ftp://...)",
        suggested_name: "web-size",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(183),
        title: "TCP relay",
        suggested_name: "tcp-relay",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(184),
        title: "UDP relay",
        suggested_name: "udp-relay",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(185),
        title: "TCP multiclient relay",
        suggested_name: "tcp-mulrelay",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(186),
        title: "Millisecond sleep",
        suggested_name: "sleep-ms",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(187),
        title: "Display date and time",
        suggested_name: "datetime",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(188),
        title: "SYSLOG server",
        suggested_name: "syslog-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(189),
        title: "SMTP server",
        suggested_name: "smtp-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(190),
        title: "Make coffee",
        suggested_name: "coffee",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(191),
        title: "Generate a password (English, French, Spanish)",
        suggested_name: "gen-password",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(192),
        title: "Spoof of packet samples : fragment, ip4opt:ssrr",
        suggested_name: "spoof-sample-ssrr",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(193),
        title: "IDENT client requesting info about an open session",
        suggested_name: "ident-query",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(194),
        title: "IDENT client creating a session and requesting its info",
        suggested_name: "ident-probe",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(195),
        title: "IDENT server",
        suggested_name: "ident-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(196),
        title: "WHOIS client",
        suggested_name: "whois",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(197),
        title: "WHOIS client guessing server",
        suggested_name: "whois-guess",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(198),
        title: "SMB/CIFS client: list shares",
        suggested_name: "smb-shares",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(199),
        title: "SMB/CIFS client: create a directory",
        suggested_name: "smb-mkdir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(200),
        title: "SMB/CIFS client: delete a directory",
        suggested_name: "smb-rmdir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(201),
        title: "SMB/CIFS client: rename a directory",
        suggested_name: "smb-mv-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(202),
        title: "SMB/CIFS client: list contents of a directory",
        suggested_name: "smb-ls",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(203),
        title: "SMB/CIFS client: delete a file",
        suggested_name: "smb-rm",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(204),
        title: "SMB/CIFS client: rename a file",
        suggested_name: "smb-mv",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(205),
        title: "SMB/CIFS client: get a file",
        suggested_name: "smb-get",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(206),
        title: "SMB/CIFS client: put a file",
        suggested_name: "smb-put",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(207),
        title: "SMB/CIFS client: recursively get a directory",
        suggested_name: "smb-get-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(208),
        title: "SMB/CIFS client: recursively put a directory",
        suggested_name: "smb-put-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(209),
        title: "SMB/CIFS client: recursively delete a directory",
        suggested_name: "smb-rm-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(210),
        title: "Web spider on command line (stay in same directory)",
        suggested_name: "spider-dir",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: true,
    },
    ToolEntry {
        id: ToolId(211),
        title: "Web spider : converts a local downloaded filename to its original url",
        suggested_name: "spider-file-to-url",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(212),
        title: "Web spider : converts an url to its local downloaded filename",
        suggested_name: "spider-url-to-file",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(213),
        title: "Display a list of IP addresses",
        suggested_name: "ip-list",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(214),
        title: "Traceroute discovery: graph of network topology",
        suggested_name: "trace-map",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(215),
        title: "Traceroute discovery (EthIp spoof)",
        suggested_name: "trace-map-eth",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(216),
        title: "Beep",
        suggested_name: "beep",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(217),
        title: "SMB/CIFS server",
        suggested_name: "smb-server",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(218),
        title: "Netwox internal validation suite",
        suggested_name: "internal-validation",
        publish: PublishKind::Hidden,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(219),
        title: "Compute cryptographic hash of a file (md5, sha, etc.)",
        suggested_name: "file-hash",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(220),
        title: "Convert a binary file to a base64 encoded file",
        suggested_name: "file-b64-enc",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(221),
        title: "Convert a base64 encoded file to a binary file",
        suggested_name: "file-b64-dec",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(222),
        title: "In a HTML file, suppress links pointing to local urls",
        suggested_name: "html-unlink-local",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
    ToolEntry {
        id: ToolId(223),
        title: "Forward an email",
        suggested_name: "smtp-fwd",
        publish: PublishKind::Release,
        needs_stdin: false,
        needs_backspace: false,
    },
];

/// 后置工具号（默认不编进发布二进制）。
pub static DEFERRED_TOOL_IDS: &[u32] = &[
    73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 98, 101, 130, 131, 132,
];
