//! Generated from netwox `tooltree.c` + `tools/*/nodes` — do not hand-edit.
//! Regenerate: `python3 scripts/gen_tooltree.py`.

/// Category node in the Search tree.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TreeCategory {
    /// Stable id (slug).
    pub id: &'static str,
    /// Display label.
    pub label: &'static str,
    /// Whether tools may attach directly.
    pub can_add_tool: bool,
    /// Child category ids.
    pub child_categories: &'static [&'static str],
}

/// All category nodes (including `main`).
pub static TREE_CATEGORIES: &[TreeCategory] = &[
    TreeCategory {
        id: "main",
        label: "MAIN MENU",
        can_add_tool: false,
        child_categories: &[
            "info",
            "netproto",
            "appproto",
            "sniff",
            "spoof",
            "record",
            "client",
            "server",
            "ping",
            "traceroute",
            "scan",
            "netaudit",
            "bruteforce",
            "remadm",
            "notnet",
        ],
    },
    TreeCategory {
        id: "info",
        label: "information",
        can_add_tool: false,
        child_categories: &["info-local", "info-remote", "info-netw"],
    },
    TreeCategory {
        id: "info-netw",
        label: "information on netw",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "info-local",
        label: "information on local computer",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "info-remote",
        label: "information on remote computer",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netproto",
        label: "network protocol",
        can_add_tool: false,
        child_categories: &[
            "netproto-eth",
            "netproto-ip",
            "netproto-udp",
            "netproto-tcp",
            "netproto-icmp",
            "netproto-arp",
        ],
    },
    TreeCategory {
        id: "netproto-eth",
        label: "Ethernet",
        can_add_tool: false,
        child_categories: &["spoof-eth", "netaudit-eth", "netproto-ip", "netproto-arp"],
    },
    TreeCategory {
        id: "netproto-ip",
        label: "IP",
        can_add_tool: false,
        child_categories: &[
            "spoof-ip",
            "netaudit-ip",
            "netproto-udp",
            "netproto-tcp",
            "netproto-icmp",
        ],
    },
    TreeCategory {
        id: "netproto-udp",
        label: "UDP",
        can_add_tool: false,
        child_categories: &[
            "spoof-udp",
            "client-udp",
            "server-udp",
            "netaudit-udp",
            "appproto-dhcp",
            "appproto-dns",
            "appproto-ntp",
            "appproto-snmp",
            "appproto-syslog",
            "appproto-tftp",
        ],
    },
    TreeCategory {
        id: "netproto-tcp",
        label: "TCP",
        can_add_tool: false,
        child_categories: &[
            "spoof-tcp",
            "client-tcp",
            "server-tcp",
            "netaudit-tcp",
            "appproto-dns",
            "appproto-ftp",
            "appproto-http",
            "appproto-ident",
            "appproto-irc",
            "appproto-nntp",
            "appproto-smb",
            "appproto-smtp",
            "appproto-telnet",
            "appproto-whois",
        ],
    },
    TreeCategory {
        id: "netproto-icmp",
        label: "ICMP",
        can_add_tool: false,
        child_categories: &["spoof-icmp", "server-icmp", "netaudit-icmp"],
    },
    TreeCategory {
        id: "netproto-arp",
        label: "ARP",
        can_add_tool: false,
        child_categories: &["spoof-arp", "server-arp", "netaudit-arp"],
    },
    TreeCategory {
        id: "appproto",
        label: "application protocol",
        can_add_tool: false,
        child_categories: &[
            "appproto-dhcp",
            "appproto-dns",
            "appproto-ftp",
            "appproto-http",
            "appproto-ident",
            "appproto-irc",
            "appproto-nntp",
            "appproto-ntp",
            "appproto-smb",
            "appproto-smtp",
            "appproto-snmp",
            "appproto-syslog",
            "appproto-telnet",
            "appproto-tftp",
            "appproto-whois",
        ],
    },
    TreeCategory {
        id: "appproto-dhcp",
        label: "dhcp",
        can_add_tool: false,
        child_categories: &["client-udp-dhcp", "server-udp-dhcp"],
    },
    TreeCategory {
        id: "appproto-dns",
        label: "dns",
        can_add_tool: false,
        child_categories: &[
            "client-udp-dns",
            "client-tcp-dns",
            "server-udp-dns",
            "server-tcp-dns",
        ],
    },
    TreeCategory {
        id: "appproto-ftp",
        label: "ftp",
        can_add_tool: false,
        child_categories: &["client-tcp-ftp", "server-tcp-ftp"],
    },
    TreeCategory {
        id: "appproto-http",
        label: "http",
        can_add_tool: false,
        child_categories: &["client-tcp-http", "server-tcp-http"],
    },
    TreeCategory {
        id: "appproto-ident",
        label: "ident",
        can_add_tool: false,
        child_categories: &["client-tcp-ident", "server-tcp-ident"],
    },
    TreeCategory {
        id: "appproto-irc",
        label: "irc",
        can_add_tool: false,
        child_categories: &["client-tcp-irc", "server-tcp-irc"],
    },
    TreeCategory {
        id: "appproto-nntp",
        label: "nntp",
        can_add_tool: false,
        child_categories: &["client-tcp-nntp", "server-tcp-nntp"],
    },
    TreeCategory {
        id: "appproto-ntp",
        label: "ntp",
        can_add_tool: false,
        child_categories: &["client-udp-ntp", "server-udp-ntp"],
    },
    TreeCategory {
        id: "appproto-smtp",
        label: "smtp",
        can_add_tool: false,
        child_categories: &["client-tcp-smtp", "server-tcp-smtp"],
    },
    TreeCategory {
        id: "appproto-smb",
        label: "smb",
        can_add_tool: false,
        child_categories: &["client-tcp-smb", "server-tcp-smb"],
    },
    TreeCategory {
        id: "appproto-syslog",
        label: "syslog",
        can_add_tool: false,
        child_categories: &["client-udp-syslog", "server-udp-syslog"],
    },
    TreeCategory {
        id: "appproto-snmp",
        label: "snmp",
        can_add_tool: false,
        child_categories: &["client-udp-snmp", "server-udp-snmp"],
    },
    TreeCategory {
        id: "appproto-telnet",
        label: "telnet",
        can_add_tool: false,
        child_categories: &["client-tcp-telnet", "server-tcp-telnet"],
    },
    TreeCategory {
        id: "appproto-tftp",
        label: "tftp",
        can_add_tool: false,
        child_categories: &["client-udp-tftp", "server-udp-tftp"],
    },
    TreeCategory {
        id: "appproto-whois",
        label: "whois",
        can_add_tool: false,
        child_categories: &["client-tcp-whois", "server-tcp-whois"],
    },
    TreeCategory {
        id: "sniff",
        label: "sniff (capture network packets)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "spoof",
        label: "spoof (create and send packets)",
        can_add_tool: false,
        child_categories: &[
            "spoof-eth",
            "spoof-ip",
            "spoof-udp",
            "spoof-tcp",
            "spoof-icmp",
            "spoof-arp",
        ],
    },
    TreeCategory {
        id: "spoof-eth",
        label: "Ethernet spoof",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "spoof-ip",
        label: "IP spoof",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "spoof-udp",
        label: "UDP spoof",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "spoof-tcp",
        label: "TCP spoof",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "spoof-icmp",
        label: "ICMP spoof",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "spoof-arp",
        label: "ARP spoof",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "record",
        label: "record (file containing captured packets)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client",
        label: "client",
        can_add_tool: false,
        child_categories: &["client-udp", "client-tcp"],
    },
    TreeCategory {
        id: "client-udp",
        label: "UDP client",
        can_add_tool: false,
        child_categories: &[
            "client-udp-generic",
            "client-udp-dhcp",
            "client-udp-dns",
            "client-udp-ntp",
            "client-udp-snmp",
            "client-udp-syslog",
            "client-udp-tftp",
        ],
    },
    TreeCategory {
        id: "client-udp-generic",
        label: "generic UDP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-udp-dhcp",
        label: "DHCP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-udp-dns",
        label: "DNS (udp) client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-udp-ntp",
        label: "NTP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-udp-snmp",
        label: "SNMP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-udp-syslog",
        label: "SYSLOG client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-udp-tftp",
        label: "TFTP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp",
        label: "TCP client",
        can_add_tool: false,
        child_categories: &[
            "client-tcp-generic",
            "client-tcp-dns",
            "client-tcp-ftp",
            "client-tcp-http",
            "client-tcp-ident",
            "client-tcp-irc",
            "client-tcp-nntp",
            "client-tcp-smb",
            "client-tcp-smtp",
            "client-tcp-telnet",
            "client-tcp-whois",
        ],
    },
    TreeCategory {
        id: "client-tcp-generic",
        label: "generic TCP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-dns",
        label: "DNS (tcp) client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-ftp",
        label: "FTP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-http",
        label: "HTTP client",
        can_add_tool: true,
        child_categories: &["client-tcp-http-spider"],
    },
    TreeCategory {
        id: "client-tcp-http-spider",
        label: "web spider (website download)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-ident",
        label: "IDENT client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-irc",
        label: "IRC client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-nntp",
        label: "NNTP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-smb",
        label: "SMB client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-smtp",
        label: "SMTP client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-telnet",
        label: "TELNET client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "client-tcp-whois",
        label: "WHOIS client",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server",
        label: "server",
        can_add_tool: false,
        child_categories: &["server-udp", "server-tcp", "server-icmp", "server-arp"],
    },
    TreeCategory {
        id: "server-udp",
        label: "UDP server",
        can_add_tool: false,
        child_categories: &[
            "server-udp-generic",
            "server-udp-dhcp",
            "server-udp-dns",
            "server-udp-ntp",
            "server-udp-snmp",
            "server-udp-syslog",
            "server-udp-tftp",
        ],
    },
    TreeCategory {
        id: "server-udp-generic",
        label: "generic UDP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-udp-dhcp",
        label: "DHCP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-udp-dns",
        label: "DNS (udp) server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-udp-ntp",
        label: "NTP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-udp-snmp",
        label: "SNMP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-udp-syslog",
        label: "SYSLOG server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-udp-tftp",
        label: "TFTP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp",
        label: "TCP server",
        can_add_tool: false,
        child_categories: &[
            "server-tcp-generic",
            "server-tcp-dns",
            "server-tcp-ftp",
            "server-tcp-http",
            "server-tcp-ident",
            "server-tcp-irc",
            "server-tcp-nntp",
            "server-tcp-smb",
            "server-tcp-smtp",
            "server-tcp-telnet",
            "server-tcp-whois",
        ],
    },
    TreeCategory {
        id: "server-tcp-generic",
        label: "generic TCP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-dns",
        label: "DNS (tcp) server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-ftp",
        label: "FTP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-http",
        label: "HTTP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-ident",
        label: "IDENT server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-irc",
        label: "IRC server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-nntp",
        label: "NNTP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-smb",
        label: "SMB server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-smtp",
        label: "SMTP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-telnet",
        label: "TELNET server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-tcp-whois",
        label: "WHOIS server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-icmp",
        label: "ICMP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "server-arp",
        label: "ARP server",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "ping",
        label: "ping (check if a computer if reachable)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "traceroute",
        label: "traceroute (obtain list of gateways)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "scan",
        label: "scan (computer and port discovery)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netaudit",
        label: "network audit",
        can_add_tool: false,
        child_categories: &[
            "netaudit-eth",
            "netaudit-ip",
            "netaudit-udp",
            "netaudit-tcp",
            "netaudit-icmp",
            "netaudit-arp",
        ],
    },
    TreeCategory {
        id: "netaudit-eth",
        label: "network audit using Ethernet",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netaudit-ip",
        label: "network audit using IP",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netaudit-udp",
        label: "network audit using UDP",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netaudit-tcp",
        label: "network audit using TCP",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netaudit-icmp",
        label: "network audit using ICMP",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "netaudit-arp",
        label: "network audit using ARP",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "bruteforce",
        label: "brute force (check if passwords are weak)",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "remadm",
        label: "remote administration",
        can_add_tool: true,
        child_categories: &[],
    },
    TreeCategory {
        id: "notnet",
        label: "tools not related to network",
        can_add_tool: true,
        child_categories: &["notnet-file"],
    },
    TreeCategory {
        id: "notnet-file",
        label: "tools working on files",
        can_add_tool: true,
        child_categories: &[],
    },
];

/// Tool id → leaf category ids (may be multiple).
pub static TOOL_TREE_PLACEMENTS: &[(u32, &[&str])] = &[
    (1, &["info-local"]),
    (2, &["info-netw"]),
    (3, &["info-remote"]),
    (4, &["info-remote"]),
    (5, &["info-remote"]),
    (6, &["info-remote"]),
    (7, &["sniff"]),
    (8, &["info-remote", "scan"]),
    (9, &["info-remote"]),
    (10, &["sniff"]),
    (11, &["sniff"]),
    (12, &["info-netw"]),
    (13, &["sniff", "spoof-eth", "spoof-ip"]),
    (14, &["spoof-eth", "spoof-ip", "record"]),
    (15, &["record"]),
    (16, &["record"]),
    (17, &["record"]),
    (18, &["record"]),
    (19, &["record"]),
    (20, &["record"]),
    (21, &["notnet"]),
    (22, &["notnet"]),
    (23, &["notnet"]),
    (24, &["info-remote", "notnet"]),
    (25, &["notnet", "notnet-file"]),
    (26, &["notnet-file"]),
    (27, &["notnet-file"]),
    (28, &["notnet-file"]),
    (29, &["notnet-file"]),
    (30, &["notnet-file"]),
    (31, &["notnet-file"]),
    (32, &["spoof-eth"]),
    (33, &["spoof-eth", "spoof-arp"]),
    (34, &["spoof-eth", "spoof-ip"]),
    (35, &["spoof-eth", "spoof-ip", "spoof-udp"]),
    (36, &["spoof-eth", "spoof-ip", "spoof-tcp"]),
    (37, &["spoof-eth", "spoof-ip", "spoof-icmp"]),
    (38, &["spoof-ip"]),
    (39, &["spoof-ip", "spoof-udp"]),
    (40, &["spoof-ip", "spoof-tcp"]),
    (41, &["spoof-ip", "spoof-icmp"]),
    (42, &["spoof-ip", "spoof-tcp"]),
    (43, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (44, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (45, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (46, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (47, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (48, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (49, &["ping"]),
    (50, &["ping"]),
    (51, &["ping"]),
    (52, &["ping"]),
    (53, &["ping"]),
    (54, &["ping"]),
    (55, &["ping"]),
    (56, &["ping"]),
    (57, &["traceroute"]),
    (58, &["traceroute"]),
    (59, &["traceroute"]),
    (60, &["traceroute"]),
    (61, &["traceroute"]),
    (62, &["traceroute"]),
    (63, &["traceroute"]),
    (64, &["traceroute"]),
    (65, &["scan"]),
    (66, &["scan"]),
    (67, &["scan"]),
    (68, &["scan"]),
    (69, &["scan"]),
    (70, &["scan"]),
    (71, &["scan"]),
    (72, &["scan"]),
    (
        73,
        &["server-arp", "server-icmp", "netaudit-arp", "netaudit-icmp"],
    ),
    (74, &["netaudit-ip"]),
    (75, &["netaudit-eth"]),
    (76, &["netaudit-tcp"]),
    (77, &["netaudit-tcp"]),
    (78, &["netaudit-tcp"]),
    (79, &["netaudit-tcp"]),
    (80, &["server-arp", "netaudit-arp"]),
    (81, &["netaudit-icmp"]),
    (82, &["netaudit-icmp"]),
    (83, &["netaudit-icmp"]),
    (84, &["netaudit-icmp"]),
    (85, &["netaudit-icmp"]),
    (86, &["netaudit-icmp"]),
    (87, &["client-tcp-generic"]),
    (88, &["client-udp-generic"]),
    (89, &["server-tcp-generic"]),
    (90, &["server-udp-generic"]),
    (91, &["server-tcp-generic"]),
    (92, &["server-udp-generic"]),
    (93, &["remadm"]),
    (94, &["remadm"]),
    (95, &["remadm"]),
    (96, &["remadm"]),
    (97, &["client-udp-syslog"]),
    (98, &["client-udp-syslog"]),
    (99, &["client-tcp-telnet"]),
    (100, &["client-tcp-telnet"]),
    (101, &["client-tcp-telnet", "bruteforce"]),
    (102, &["client-udp-dns", "client-tcp-dns"]),
    (103, &["client-udp-dns", "client-tcp-dns"]),
    (104, &["server-udp-dns"]),
    (105, &["server-udp-dns"]),
    (106, &["client-tcp-smtp"]),
    (107, &["client-tcp-nntp"]),
    (108, &["client-tcp-nntp"]),
    (109, &["client-tcp-nntp"]),
    (110, &["sniff", "spoof-eth"]),
    (111, &["client-tcp-ftp"]),
    (112, &["client-tcp-ftp"]),
    (113, &["client-tcp-ftp"]),
    (114, &["client-tcp-ftp"]),
    (115, &["client-tcp-ftp"]),
    (116, &["client-tcp-ftp"]),
    (117, &["client-tcp-ftp"]),
    (118, &["client-tcp-http"]),
    (119, &["client-tcp-http"]),
    (120, &["client-tcp-http"]),
    (121, &["client-tcp-http"]),
    (122, &["client-tcp-http"]),
    (123, &["client-tcp-http"]),
    (124, &["client-tcp-http"]),
    (125, &["server-tcp-http"]),
    (126, &["server-tcp-http", "remadm"]),
    (127, &["notnet-file"]),
    (128, &["notnet-file"]),
    (129, &["notnet-file"]),
    (130, &["client-tcp-ftp", "bruteforce"]),
    (131, &["client-tcp-http", "bruteforce"]),
    (132, &["client-tcp-http", "bruteforce"]),
    (133, &["client-tcp-http", "notnet"]),
    (134, &["client-tcp-http", "notnet"]),
    (135, &["notnet"]),
    (136, &["client-tcp-ftp", "client-tcp-http"]),
    (137, &["client-tcp-http-spider"]),
    (138, &["client-tcp-http-spider"]),
    (139, &["client-tcp-http-spider"]),
    (140, &["spoof-eth", "spoof-ip"]),
    (141, &["spoof-eth", "spoof-ip", "spoof-udp"]),
    (142, &["spoof-eth", "spoof-ip", "spoof-tcp"]),
    (143, &["spoof-eth", "spoof-ip", "spoof-icmp"]),
    (144, &["spoof-ip"]),
    (145, &["spoof-ip", "spoof-udp"]),
    (146, &["spoof-ip", "spoof-tcp"]),
    (147, &["spoof-ip", "spoof-icmp"]),
    (148, &["ping"]),
    (149, &["ping"]),
    (150, &["scan"]),
    (151, &["scan"]),
    (152, &["client-tcp-irc"]),
    (153, &["client-tcp-irc"]),
    (154, &["client-tcp-irc"]),
    (155, &["server-tcp-generic"]),
    (156, &["client-tcp-generic"]),
    (157, &["server-udp-generic"]),
    (158, &["client-udp-generic"]),
    (159, &["client-udp-snmp"]),
    (160, &["client-udp-snmp"]),
    (161, &["client-udp-snmp"]),
    (162, &["client-udp-snmp"]),
    (163, &["client-udp-snmp"]),
    (164, &["client-udp-snmp"]),
    (165, &["client-udp-tftp"]),
    (166, &["client-udp-tftp"]),
    (167, &["server-udp-tftp"]),
    (168, &["server-tcp-ftp"]),
    (169, &["info-local"]),
    (170, &["server-tcp-telnet"]),
    (171, &["client-udp-dhcp"]),
    (172, &["client-tcp-nntp"]),
    (173, &["client-tcp-nntp"]),
    (174, &["client-tcp-ftp"]),
    (175, &["client-tcp-ftp", "client-tcp-http"]),
    (176, &["client-udp-tftp"]),
    (177, &["client-tcp-smtp"]),
    (178, &["client-tcp-irc"]),
    (179, &["client-udp-dhcp"]),
    (180, &["client-udp-ntp"]),
    (181, &["server-udp-ntp"]),
    (182, &["client-tcp-ftp", "client-tcp-http"]),
    (183, &["server-tcp-generic", "client-tcp-generic"]),
    (184, &["server-udp-generic", "client-udp-generic"]),
    (185, &["server-tcp-generic", "client-tcp-generic"]),
    (186, &["notnet"]),
    (187, &["notnet"]),
    (188, &["server-udp-syslog"]),
    (189, &["server-tcp-smtp"]),
    (190, &["notnet"]),
    (191, &["notnet", "bruteforce"]),
    (192, &["spoof-ip", "spoof-udp", "spoof-tcp", "spoof-icmp"]),
    (193, &["client-tcp-ident"]),
    (194, &["client-tcp-ident"]),
    (195, &["server-tcp-ident"]),
    (196, &["client-tcp-whois"]),
    (197, &["client-tcp-whois"]),
    (198, &["client-tcp-smb"]),
    (199, &["client-tcp-smb"]),
    (200, &["client-tcp-smb"]),
    (201, &["client-tcp-smb"]),
    (202, &["client-tcp-smb"]),
    (203, &["client-tcp-smb"]),
    (204, &["client-tcp-smb"]),
    (205, &["client-tcp-smb"]),
    (206, &["client-tcp-smb"]),
    (207, &["client-tcp-smb"]),
    (208, &["client-tcp-smb"]),
    (209, &["client-tcp-smb"]),
    (210, &["client-tcp-http-spider"]),
    (211, &["client-tcp-http-spider"]),
    (212, &["client-tcp-http-spider"]),
    (213, &["notnet"]),
    (214, &["traceroute", "scan"]),
    (215, &["traceroute", "scan"]),
    (216, &["notnet"]),
    (217, &["server-tcp-smb"]),
    (218, &["info-netw"]),
    (219, &["notnet-file"]),
    (220, &["notnet-file"]),
    (221, &["notnet-file"]),
    (222, &["notnet"]),
    (223, &["client-tcp-smtp"]),
];
